services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - media_volume:/app/media
    ports:
      - "8000:8000"
    # no depends_on here

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.local
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  media_volume:
